ALTER TABLE fish
  ADD COLUMN IF NOT EXISTS scientific_name VARCHAR(200) DEFAULT NULL AFTER name,
  ADD COLUMN IF NOT EXISTS category VARCHAR(100) DEFAULT NULL AFTER scientific_name,
  ADD COLUMN IF NOT EXISTS water_type VARCHAR(100) DEFAULT NULL AFTER category;

